### ISSUE TITLE
Expressive Components

### ISSUE THREAD

**Issue by amcdnl** [Swimlane/angular-data-table#1]
Expressive components is a interesting approach to component design.  So rather than have 1 element thats on the page, you have a expressive markup that would represent what you would be composing in the model.  For example:

```
<data-table>
   <data-table-header>
       <data-table-header-col can-resize="true">{{money}}<data-table-header-col>
  </data-table-header>
  <data-table-body>
    <data-table-body-row ng-repeat="row in rows">
        <data-table-body-cell>
            {{row.name}}
        </data-table-body-cell>
    </data-table-body-row>
  </data-table-body>
</data-table>
```

There are a few challenges when going down this route such as transclusion, scoping, dealing with our complicated layouts and keep the api easy.

Simpler grid project implementing this: https://github.com/daniel-nagy/md-data-table

**Comment by amcdnl** [comment]
I noticed Angular Material uses some custom transcludes that we might be able to leverage, example:

```
function MdChipTransclude ($compile, $mdUtil) {
  return {
    restrict: 'EA',
    terminal: true,
    link: link,
    scope: false
  };
  function link (scope, element, attr) {
    var ctrl = scope.$parent.$mdChipsCtrl,
        newScope = ctrl.parent.$new(false, ctrl.parent);
    newScope.$$replacedScope = scope;
    newScope.$chip = scope.$chip;
    newScope.$mdChipsCtrl = ctrl;
    element.html(ctrl.$scope.$eval(attr.mdChipTransclude));
    $compile(element.contents())(newScope);
  }
}
```

**Comment by amcdnl** [comment]
Maybe rather than try to go all the way down to the cell level of expressive-ness, its just the top layer like Facebook's react data table does:

```
React.render(
  <Table
    rowHeight={50}
    rowGetter={rowGetter}
    rowsCount={rows.length}
    width={5000}
    height={5000}
    headerHeight={50}>
    <Column
      label="Col 1"
      width={3000}
      dataKey={0}
    />
    <Column
      label="Col 2"
      width={2000}
      dataKey={1}
    />
  </Table>
);
```

**Comment by brianfeister** [comment]
In my various uses of a table, I tend to want buttons and functionality inside table cells, so for me the second (React Facebook data table) templating method is not expressive enough for me.

**Comment by amcdnl** [comment]
@brianfeister I was thinking we could let you pass a template or maybe inner contents would be the template and transclude?

**Comment by brianfeister** [comment]
That works for me, worked well when I used ngTable http://ng-table.com/, they do the same

**Comment by amcdnl** [comment]
Posted a question on StackOverflow about design and a few technical questions - http://stackoverflow.com/questions/30845397/angular-expressive-directive-design

**Comment by amcdnl** [comment]
I believe this should resolve this!  Would love feedback!  https://github.com/Swimlane/angular-data-table/commit/84bd45b5d0d7e933f0906b4e864f3c639ddf556c

I think its worth noting that `ng-repeat` would probably not work here since columns are processed pre-compilation.

**Comment by amcdnl** [comment]
UPDATE: things like `ng-repeat` do work now.
