### ISSUE TITLE
If the image source changes, then the image is not updated in the grid

### ISSUE THREAD

**Issue by kuzman** [Swimlane/angular-data-table#100]
HI,

I have a custom cell render, an img tag. The issue I have is that the 'ng-src' changes and it is not reflected in the grid. When inspecting the scope of the row I can see that the model is updated, but the grid is not.

**Comment by amcdnl** [comment]
Demo plz?

**Comment by kuzman** [comment]
well this is the closest to my situation: http://codepen.io/anon/pen/vNozNE

**Comment by amcdnl** [comment]
Interesting.  I was able to reproduce and posted a sample here: https://github.com/Swimlane/angular-data-table/blob/master/demos/updating.html

I'll need to investigate more.

**Comment by kuzman** [comment]
fixed in 0.4.11
