### ISSUE TITLE
Scope values binding does not work with angular 1.3

### ISSUE THREAD

**Issue by SantjagoCorkez** [Swimlane/angular-data-table#102]
http://codepen.io/anon/pen/jbgoOe

This is just a fork of demo pen with:
underscore.js attached;
angular version 1.3.20
datatable version 0.4.20 (master)

You could see it's not working at all (dt-controllers use default options instead of those bound via `options` property. Switching to `data-*` property naming does not help.

**Comment by SantjagoCorkez** [comment]
OK. I've found it:

every directive's definition is corrupt. Instead of `scope: true, bindToController: {...}` it must be `scope: {...}, bindToController: true`

**Comment by SantjagoCorkez** [comment]
Is there any way to support angular 1.3?

**Comment by amcdnl** [comment]
@SantjagoCorkez interesting, can you do a PR to correct?  I do not plan on supporting 1.3 esp with 1.5 out soon.  Sorry.

**Comment by amcdnl** [comment]
Fixed in 0.4.11
