### ISSUE TITLE
dtm directive is not imported

### ISSUE THREAD

**Issue by ngodfraind** [Swimlane/angular-data-table#103]
Hello,

I tried to do it myself by updating dataTable.js and running gulp release but I'm an angular/node newb and it kinda failed (I have following error now: "the Argument 'MenuController' is not a function, got undefined.").
I assume I'm missing something.

**Comment by amcdnl** [comment]
see https://github.com/Swimlane/angular-data-table/blob/master/demos/columnadd.html#L66

The menu and popup directives are not built as part of this project.  you will need to compile those yourself ... they are mainly for demo.

**Comment by ngodfraind** [comment]
I'll look how it's done and make my own then. Thanks.
