### ISSUE TITLE
checkbox selection doesn't work properly (with pager)

### ISSUE THREAD

**Issue by ngodfraind** [Swimlane/angular-data-table#104]
Hi again,

On 0.4.10
When I click on a checkbox, my js debugger says 'event is not defined'. I can give you the complete stacktrace if you want. It happens even if I don't use the pager.

On 0.4.8 it almost worked. My $scope.selected array was good even when I changed pages, but when I came back to previous pages, the selection disappeared (but $scope.selected still contained everything I wanted so I assume it's only a display bug).

**Comment by amcdnl** [comment]
@jsheely interesting...

Related to: https://github.com/Swimlane/angular-data-table/pull/97

**Comment by jsheely** [comment]
I'll check it out. Off the top of my head the issue would result if the function gets called from something other than an event. (click in our case).

Without looking at the code my guess is that the pager manually goes back in to check each item and fires the function to check it. But I will confirm.

I will update my demo to use a pager and push an update.

**Comment by ngodfraind** [comment]
More infos on checkboxes:

Wen I try to initialize my $scope.selected array (I want some rows already checked) the behaviour completly changed for me (but I may be doing it wrong). The $scope.selected didn't seem to update anymore but I could pre check rows if I wanted.

I couldn't find the event triggered when a checkbox is unchecked.

The 'select all' doesn't seem to work properly either.

**Comment by amcdnl** [comment]
Should be fixed in 0.4.11

**Comment by ngodfraind** [comment]
It works now and I kind of understand how the selection is handled.

Thanks.
