### ISSUE TITLE
Dynamic columns resizing

### ISSUE THREAD

**Issue by kuzman** [Swimlane/angular-data-table#106]
Hi,

I might just don't know the right config option, but for example I have an md-card that contains the data-table and which can be resized. The table is resized, but not the columns. I have tried forceFillColumns option, the flexGrow option, but no success. Am I doing something wrong or maybe the datatable does not resize the columns?

**Comment by marjan-georgiev** [comment]
This is a known issue and we're working on it. Should be fixed soon.

**Comment by amcdnl** [comment]
This should be closed in latest.

**Comment by kuzman** [comment]
thanks, pls update bower.json with the new version :)
