### ISSUE TITLE
Embedding within custom directive

### ISSUE THREAD

**Issue by pan-henryk** [Swimlane/angular-data-table#113]
I am trying to embed data-table within my own custom directive. It works fine, if options are declared in controller (one set for table instances, which are spawned dynamically). Unfortunately data table does not allow to declare them within link function of the directive (it's too late for its lifecycle). What's the best way to do it?

**Comment by amcdnl** [comment]
Example?

**Comment by pan-henryk** [comment]
I made a quick example based on one of your demos:

http://codepen.io/anon/pen/obbeNY
1. It does not work when table options are defined in link function
2. It works properly when I move table options to controller function

**Comment by amcdnl** [comment]
This is a angular lifecycle dealio. Links happen later, so you need to put them in a controller if you need them to happen first. DT has a delicate timing lifecycle so as soon as possible its ideal to set options.
