### ISSUE TITLE
Internet explorer complains about Object.assign use

### ISSUE THREAD

**Issue by pan-henryk** [Swimlane/angular-data-table#114]
Use of Object.Assign seems to be unsupported for IE (dataTable.helpers, line 2006).
I wonder if it can be safely replaced with jQuery.extend method?

I am also having problems with Symbol.iterator (yes, I know you mention ES6 on main page, but these seems to be minor changes that would allow IE compliance)

**Comment by amcdnl** [comment]
Try using the ES6 version and building it with babel yourself.
