### ISSUE TITLE
issue with columns width

### ISSUE THREAD

**Issue by kuzman** [Swimlane/angular-data-table#116]
if the width of the column is set less than the default min-width (150), then the width setting is not taken into account

**Comment by marjan-georgiev** [comment]
You can override the min-width property of the column. But maybe we should disregard it if the width is set explicitly.

**Comment by amcdnl** [comment]
@kuzman any feedback?

**Comment by kuzman** [comment]
I am working with a workaround, but I think that there should be a fix. the min-width should be taken from the width option when width<min-width
