### ISSUE TITLE
Responsive virtual pagination 

### ISSUE THREAD

**Issue by BenBrostoff** [Swimlane/angular-data-table#120]
Hey @amcdnl - first off, thanks for a great library. I wanted to ask whether virtual paging is possible when  the height of the table is not fixed. It seems to me that <code>paging</code> is never invoked if the height of the table is not fixed; <a href="http://codepen.io/anon/pen/jWVrWP" target="_blank"> please see a demo here</a> where all I have altered is the height of <code>.dt</code> to be a percentage. Thanks again.

**Comment by amcdnl** [comment]
Thanks!

Ya, unfortunately, it needs to have a fixed height. I've actually never seen a grid/table with virtual that doesnt' require that. It needs to measure the total height available / the row height to calculate how many pages there are.

If you want full height, use abs positioning. `position:absolute;top:0;left:0;right:0;bottom:0`.
