### ISSUE TITLE
Paging links numbers to rows instead of pages

### ISSUE THREAD

**Issue by geoervin** [Swimlane/angular-data-table#130]
Reviewing the demo and also with a short test project I found the the paging to work in a nonstandard way. It seems the numbers are linked to rows instead of a group of rows. This is the case with the online demo and even when I set a size option with no scrollbar (normal paging).  Have I just missed something obvious?

**Comment by amcdnl** [comment]
So virtual paging with a scrollbar is linked to the row. It calculates the grid height, location, number of rows, and height of rows to determine what page 'theortically' that it should be on.

Fixed/no scrollbar paging with page sizes, etc should work like expected.  Can you show me case where you don't see that happening? Maybe walk me through it?

**Comment by geoervin** [comment]
I have attempted to reproduce my local results using the options from the regular paging demo - 
https://github.com/Swimlane/angular-data-table/blob/master/demos/paging.html. 
The codepen was modified from the virtual online example to match the demo but it doesn't produce any rows which is a different problem from pagination.
http://codepen.io/geoervin/pen/eJEYpP
