### ISSUE TITLE
Column Pinning is not Smooth

### ISSUE THREAD

**Issue by rs112299** [Swimlane/angular-data-table#133]
As we Horizontally Scroll the table two things happens:
1. Header Scrolling is not smooth
2. Those column whom we have pinned are moving along two,they do not work smoothly

**Comment by amcdnl** [comment]
Can you provide a demo?

**Comment by rs112299** [comment]
http://codepen.io/rs112299/pen/QyOmbE

**Comment by rs112299** [comment]
@amcdnl are you able to see?

**Comment by marjan-georgiev** [comment]
I see the behavior on Firefox and Edge, but not on Chrome.

**Comment by amcdnl** [comment]
There isn't really a ton we can do here, its the angular digest cycle. We already super optimized it and bypass it even in some cases.

**Comment by amcdnl** [comment]
@rs112299 we are planning to move this to Angular2 which I think will solve many of these issues. I'm closing this issues as its not really possible given my pure A1 implementation and will address with A2 implementation.
