### ISSUE TITLE
Table with fixed header

### ISSUE THREAD

**Issue by PsyGik** [Swimlane/angular-data-table#138]
I'm trying to achieve a fixed header look for the table. Setting `scrollbarV: true` does the trick, but the height of the table changes. 

![screen shot 2016-02-01 at 11 37 43 pm](https://cloud.githubusercontent.com/assets/5432911/12726329/054bc5e2-c93d-11e5-9357-3547d65bbdde.png)

Setting `scrollbarV: false` makes the header scroll along with the rows, but the table height is 100% of the parent container.

![screen shot 2016-02-01 at 11 38 19 pm](https://cloud.githubusercontent.com/assets/5432911/12726330/05e85592-c93d-11e5-89be-3db0024cc75e.png)

**Comment by amcdnl** [comment]
can you make a demo?

**Comment by PsyGik** [comment]
@amcdnl here is a codepen: http://codepen.io/anon/pen/xZJLKR

**Comment by PsyGik** [comment]
@amcdnl any leads?

**Comment by amcdnl** [comment]
You can't really accomplish this without making the table height 100%. You would need to use something like a affix plugin to do this. I'd love to see what you come up with and happy to merge if you find a clean solution.
