### ISSUE TITLE
Browser Compatability

### ISSUE THREAD

**Issue by HariKiran9** [Swimlane/angular-data-table#139]
Unable to run demo in IE11, Woring fine in Chrome.

**Comment by kasajian** [comment]
Hari, I would recommend using this component altogether if you're planning on using Internet Explorer 11.   The fact that it wasn't test on Internet Explorer 11 indicates that it's not a high-priority and should be a clue as to where development effort is being focused on.   I think that would really be the safest conclusion.

**Comment by amcdnl** [comment]
Ya, we only target latest - 1.

PRs are always welcome!

**Comment by kasajian** [comment]
@amcdnl I'm not sure I understand your comment.  Internet Explorer 11 is the latest version of that browser.
