### ISSUE TITLE
Unable to Resize the Last Column

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#14]
Unable to Resize the Last Column.

![image](https://cloud.githubusercontent.com/assets/563166/8298241/cba8d07c-1998-11e5-8f32-d5f4a00e6456.png)

unable to see the 'seconds' fully. it always show the 'secon...'.

**Comment by amcdnl** [comment]
@shreeram its actually turned off in the CSS.  See: https://github.com/Swimlane/angular-data-table/blob/master/src/data-table.less#L125

Typically you would just resize the column to the left of it when using column filling to make occupy more space.
