### ISSUE TITLE
Context Menu Right Click on Row

### ISSUE THREAD

**Issue by HariKiran9** [Swimlane/angular-data-table#140]
Can we angular-data-table support Context Menu Right Click on Row

**Comment by amcdnl** [comment]
The table is flexible enough you can sling your own using templates and such.

I specifically avoid adding these type of features to the core. I want to keep things light and true to the core of just a table.

**Comment by HariKiran9** [comment]
Can we capture the Mouse Events like onClick, onDoubleClick, onMouseUp, onMouseDown, Row Hiding, Row Sizing, changing of selected Row.

**Comment by amcdnl** [comment]
So your proposing exposing events for all the different types of interactions with rows?

**Comment by HariKiran9** [comment]
yes.. actually i need to highlight the row for the previous visited/clicked rows/records..
Only few event were available in the API.

**Comment by Quixomatic** [comment]
Was the row right click event ever exposed? Also is there any access to the row container through use of templates or something? I'd like to add some attribute directives to it.
