### ISSUE TITLE
Order table server side

### ISSUE THREAD

**Issue by tipodisimmia** [Swimlane/angular-data-table#146]
I need to order the table on server side, so i can order these  before showing the results to the user.
This feature consist to reload the query and pagination when the user click on a sortable column and disable the client side pagination for this column or for all columns.

Thanks

**Comment by amcdnl** [comment]
Look at how paging works: https://github.com/Swimlane/angular-data-table/blob/master/demos/paging.html and listen for the `onSort` event: https://github.com/Swimlane/angular-data-table/blob/master/src/components/DataTableController.js#L164

**Comment by tipodisimmia** [comment]
Thanks

**Comment by tipodisimmia** [comment]
I'm reading the code, the point is that when the sort columns are clicked, i need to request new data to the server.
In this example http://codepen.io/anon/pen/YwmZxe?editors=1010 i'm trying to define the  onSort method  in order to insert there the request of new data and update the table, but is not working .

Thanks
