### ISSUE TITLE
DataTable not work in IE11, by modify gulp build script can solve it

### ISSUE THREAD

**Issue by bonbonmark** [Swimlane/angular-data-table#149]
In IE11 we found that Object.assign not supported, currently we use this [babel plugin](https://www.npmjs.com/package/babel-plugin-object-assign) to let it worked in IE11. And we can modify gulpfile.js to add this plugin in both compile and release to make datatable work in IE11.

var compilerOptions = { 
  modules: 'system',
  moduleIds: false,
  comments: true,
  compact: false,
*\*  plugins: ["object-assign"]**
};

gulp.task('release-es6-helpers', function () {
  return gulp.src('release/dataTable.es6.js')
    .pipe(babel({
      comments: false,
      compact: false,
      modules: 'umd',
      moduleId: 'DataTable',
*\*      plugins: ["object-assign"]**
    }))
    .pipe(ngAnnotate({
      gulpWarnings: false
    }))
    .pipe(header(banner, { pkg: pkg }))
    .pipe(rename('dataTable.helpers.js'))
    .pipe(gulp.dest("release/"))
});

**Comment by amcdnl** [comment]
I don't want to include these polyfills out of the box as myself and many other apps are already poylfilling these which would result in double code download. 

You should just manually include a polyfill yourself if you are not already using one, its really helpful even outside this context :)
