### ISSUE TITLE
Unable to Disable the vertical scroll bar 

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#15]
I need to table without vertical scroll bars. but i have no options disable the vertical scroll bars in table. pagination required without scrollable body. 
![image](https://cloud.githubusercontent.com/assets/563166/8329670/d4102862-1aad-11e5-90d6-8c2fed81bfc9.png)

**Comment by amcdnl** [comment]
The basic demo demonstrates this - check out the options here -
https://github.com/Swimlane/angular-data-table/blob/master/src/defaults.js#L8

**Comment by shreeram** [comment]
Hi,
Thanks for your response.
I can modify the defaults with pagination and without vertical scroll bar.

Regards,
Ramesh A

**Comment by shreeram** [comment]
Hi,

table not loading when scrollbarV option set to false.

![image](https://cloud.githubusercontent.com/assets/563166/8345709/d90d7838-1b25-11e5-9a1a-39d77a2bc106.png)

```
System.import('data-table').then(function(dt){

    var module = angular.module('app', [ dt.default.name ]);

    module.controller('HomeController', function($scope, $http){
      var data;

      $scope.options = {
        rowHeight: 50,
        headerHeight: 50,
        footerHeight: 50,
        columns: [
          { name: "Name", prop: "name" },
          { name: "Gender", prop: "gender" },
          { name: "Company", prop: "company" }
        ],
        columnMode: 'force',
       scrollbarV: false,
        paging: {
          externalPaging: true
        }
      };

      $scope.paging = function(offset, size){
        $http.get('/demos/data/100.json').success(function(d) {
          $scope.options.paging.count = d.length;
          var set = d.splice(offset, size);
          if(!$scope.data){
            $scope.data = set;
          } else {
            // only insert items i don't already have
            set.forEach(function(r, i){
              var idx = i + (offset * size);
              $scope.data[idx] = r;
            });
          }
          console.log('paging!', offset, size)
        });
      };
    });

  });
```

**Comment by amcdnl** [comment]
So no vertical and external paging does not work.  Got it.  I'll take a look later this week.
