### ISSUE TITLE
[tree-mode] How set custom icon (svg, png)

### ISSUE THREAD

**Issue by MikeElghali** [Swimlane/angular-data-table#151]
Hi,

For column which contain **isTreeColumn** property, how i can set custom icon ?
e.g : icon: 'path/to/icon.svg'

The documentation doesn't explain but actually we need to load this stylesheet :
`<link href="http://fontastic.s3.amazonaws.com/Jnf54BZCm7mSjGCxNRbfp3/icons.css" rel="stylesheet">`

Thanks,
Regards.

**Comment by amcdnl** [comment]
Just replace icon font with your own, see the classes I'm using: https://github.com/Swimlane/angular-data-table/blob/master/src/components/body/CellController.js#L35

**Comment by MikeElghali** [comment]
Oh the response time is awesome :+1: 

Thanks.
