### ISSUE TITLE
Example codepen causes mixed content

### ISSUE THREAD

**Issue by OmgImAlexis** [Swimlane/angular-data-table#154]
The codepen examples you have on https://swimlane.github.io/angular-data-table don't use https for their resources which means they never end up loading if you've loaded the github.io page over https.

![screen shot 2016-03-21 at 3 55 27 am](https://cloud.githubusercontent.com/assets/6525926/13905759/d6e16ed0-ef18-11e5-9718-b49e0b9da421.png)

**Comment by amcdnl** [comment]
Thats odd, I've never seen this.

**Comment by amcdnl** [comment]
@marjan-georgiev we need to make the pens use ``//blah.com` vs prefixing it with `http://`

**Comment by amcdnl** [comment]
should be fixed now

**Comment by OmgImAlexis** [comment]
The main pen on the homepage is still causing mixed content issues.

![screen shot 2016-05-28 at 4 29 49 pm](https://cloud.githubusercontent.com/assets/6525926/15628128/7781197c-24f1-11e6-8b7d-f8a2632eba7d.png)
