### ISSUE TITLE
Body height

### ISSUE THREAD

**Issue by ghost** [Swimlane/angular-data-table#155]
Hi,

Is there a way to tell to the data table to grow the body height to take all the available space?
Currently, the height is set to 300px by default in `DataTableDirective.js`.

**Comment by amcdnl** [comment]
Set the parent container height. If you want it to take up the full screen you can do:

```
      .dt{
        position:absolute;
        top:0;
        left:0;
        bottom:0;
        right:0;
        height:100%;
        overflow-x: hidden;
      }
```

like this demo:https://github.com/Swimlane/angular-data-table/blob/master/demos/perf-horzscroll.html
