### ISSUE TITLE
ui-router and $scope.selected data 

### ISSUE THREAD

**Issue by rjpcasalino** [Swimlane/angular-data-table#164]
I'm using ui-router for state management and I'm looking for guidance on how to actually transfer some row's data on a click event to a different state (a sidenav slides with the row's data).

I've searched the web, and I know about $rootScope and such, but I'm wondering how this would work if the row's data is attached to the `dtable` directive?

I'm fairly new to Angular and Data-Table so please forgive me if this doesn't make the most sense.

**Comment by marjan-georgiev** [comment]
You can use the `on-row-click` or `on-select` attributes to define your handler, and then navigate to the different state from there, passing the row's data object.

You can see how the click and select events are used here: http://codepen.io/marjan-georgiev/pen/oXpMev
