### ISSUE TITLE
Set options in html?

### ISSUE THREAD

**Issue by dylandechant** [Swimlane/angular-data-table#169]
Is it possible to set options in the html?

Maybe that isn't the right question.

I am defining my columns in my html:

``` html
<dtable options="options" rows="opportunities" on-row-click="onRowClick(row)" class="material dt">
  <column name="Name" width="300" flex-grow="2"></column>
  <column name="Stage">{{$row.stage}}</column>
  <column name="Probability">
    <strong>{{$row.probability}} %</strong>
  </column>
  <column name="Status">{{$row.status}}</column>
  <column name="NSR">{{$row.nsr | currency:$row.currency+' $ '}}</column>
  <column name="Deadline">{{$row.endDate | date:'MM/dd/yyyy'}}</column>
  <column name="Office">{{$row.primaryOffice}}</column>
  <column name="Practice">{{$row.primaryPractice}}</column>
  <column name="Quick View"></column>
</dtable>
```

Some of these I would like to be sortable. But if I define these columns in the `$scope.options` They are overwritten by the html columns.  I am running into this problem with the checkbox selection as well.

Is there a way to do something like this:

``` html
<column name="Name" width="300" flex-grow="2" is-checkbox-column="true"></column>
```

?

Thanks!

**Comment by amcdnl** [comment]
Did you figure out a solution @dylandechant  ?

**Comment by dylandechant** [comment]
@amcdnl Not really, just some work arounds. I realized there are options for a template which helped mitigate some of the issues.  Still not ideal due to readability and maintainability but will get the job done for now.  Thanks!
