### ISSUE TITLE
ReferenceError: define is not defined

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#17]
I got this error. Table is not loaded. :(

ReferenceError: define is not defined
https://cdn.rawgit.com/Swimlane/angular-data-table/master/release/data-table.js
Line 9

**Comment by shreeram** [comment]
please explain.. how to refer the data table without system.js. i just want to refer datatable.js itself without any libraries.

**Comment by shreeram** [comment]
this url also not working with same error defined above.

http://swimlane.github.io/angular-data-table/

**Comment by amcdnl** [comment]
@shreeram they are working for me, which one is busted for you?

**Comment by shreeram** [comment]
i like to integrate the angular data table into my current angular application. i am using angular material. what are dependency required for angular data table.

**Comment by shreeram** [comment]
my code:
&lt;script src=&quot;https://ajax.googleapis.com/ajax/libs/angularjs/1.3.15/angular.min.js &quot;&gt;&lt;/script&gt;
    &lt;script src=&quot;https://cdn.rawgit.com/Swimlane/angular-data-table/master/release/data-table.helpers.min.js &quot;&gt;&lt;/script&gt;

&lt;script&gt;
var module = angular.module('app', ['data-table']);

module.controller('MyController', function($scope, $http) {
  $scope.options = {
    rowHeight: 50,
    headerHeight: 50,
    footerHeight: false,
    scrollbarV: false,
    selectable: false,
    columns: [{
      name: &quot;Name&quot;,
      width: 300
    }, {
      name: &quot;Gender&quot;
    }, {
      name: &quot;Company&quot;
    }]
  };

  $http.get('https://cdn.rawgit.com/Swimlane/angular-data-table/master/demos/data/100.json').success(function(data) {
    $scope.data = data;
  });

});
&lt;/script&gt;
Errors:

![capture](https://cloud.githubusercontent.com/assets/563166/8382774/b48caf54-1c67-11e5-82be-c94da35e387c.PNG)

**Comment by shreeram** [comment]
its working for me. Thanks.
