### ISSUE TITLE
What is options.rowHeight for?  (potential bug with rowHeight === 'auto')

### ISSUE THREAD

**Issue by dleblanc10** [Swimlane/angular-data-table#175]
Trying to understand what `options.rowHeight` is for.  From the Tall Rows example I expected it to set the height property or set a minimum row height.  I see that it's also used for paging and scrolling.  

I found this code in ADT:

``` javascript
{
    key: "rowStyles",
    value: function rowStyles(row) {
        var styles = {};
        if (this.options.rowHeight === 'auto') {
          styles.height = this.options.rowHeight + 'px';
        }
        return styles;
    }
}
```

 Setting height to 'autopx' doesn't make any sense.  Also `if rowHeight === 'auto'` I'm pretty sure the paging calculations will blow up.  I confirmed by using 'auto' on the Virtual Paging demo and it caused that sample to completely hang.

A potential fix for this would be:

``` javascript
if (this.options.rowHeight > 0) {
  styles.height = this.options.rowHeight + 'px';
}
```

Pretty sure the code above has a bug but would also like to know what rowHeight is intended to do.

**Comment by amcdnl** [comment]
Row height is used to calculate virtual scroll page offset. For virtual it can NOT be auto. 

We should probably add some messaging around this.

**Comment by dleblanc10** [comment]
then the comparison to 'auto' should be a bug, right?

**Comment by dleblanc10** [comment]
If row height is only for virtual scrolling offset should the column height be controlled via CSS?

**Comment by amcdnl** [comment]
Auto does mean it calcs by CSS. It explicitly does NOT set it then.

No, not really a bug just better docs.

**Comment by dleblanc10** [comment]
thanks for clarifying that definitely wasn't obvious.
