### ISSUE TITLE
Angular-data-table does not work when using requireJS along with Angular

### ISSUE THREAD

**Issue by MyNameIsKippo** [Swimlane/angular-data-table#176]
If I load angular-data-table using script tags, everything works fine and without any issues.

However, when trying to load both Angular and angular-data-table using requireJS, angular spits out the following error:

Error: [$injector:modulerr] Failed to instantiate module data-table due to:
Error: [$injector:nomod] Module 'data-table' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

A plunker example of the error can be found here: https://plnkr.co/edit/OrAxjza6ow2bkdlPS5z7?p=preview

Any help is very much appreciated!!

**Comment by forceuser** [comment]
I think it is because data-table module defined with the name
`define("DataTable", ["exports", "module"], factory);`
https://github.com/Swimlane/angular-data-table/blob/master/release/dataTable.helpers.js#L9

from the requirejs [docs](http://requirejs.org/docs/api.html#modulename):

> You can explicitly name modules yourself, but it makes the modules less portable -- if you move the file to another directory you will need to change the name. It is normally best to avoid coding in a name for the module and just let the optimization tool burn in the module names. The optimization tool needs to add the names so that more than one module can be bundled in a file, to allow for faster loading in the browser.

So it better to remove name from module definition to make it more portable

**Comment by amcdnl** [comment]
The definition is generated on the fly in the gulp script.

To be honest, I have no desire to support RequireJS. Its completely dead and even the author somewhat recognizes this as he has been talking about ES6 Modules on twitter lately.
