### ISSUE TITLE
bower support

### ISSUE THREAD

**Issue by maxstoyanov** [Swimlane/angular-data-table#18]
NPM and JSPM already works, but bower is not supported. Is there a special reason for it?

I use bower because not every library uses npm and I don't want to integrate two different package manages for my frontend.

What do you think?

**Comment by amcdnl** [comment]
The great thing about jspm, anything that has a github repo can be used.  `jspm install github:Swimlane\angular-data-table` ... so even if something is not on bower ( which i had a few when i used bower ) you can still use it.  Also there is a bower plugin for jspm too.

If I get a lot of requests, I'll add it but i'd suggest you look into jspm.  Its the way of the future, all the new angular projects are using it too.  its easy to convert over from bower too.

**Comment by jdlindu** [comment]
+1 for bower support

**Comment by andrea-vega** [comment]
+1 bower
