### ISSUE TITLE
dataTable.js:89 Uncaught ReferenceError: babelHelpers is not defined

### ISSUE THREAD

**Issue by trusktr** [Swimlane/angular-data-table#188]
This bug has been around for a while. Please fix. Thanks.

**Comment by trusktr** [comment]
Oh ok, nevermind, import the dataTable.helpers.js file instead.

**Comment by ghost** [comment]
How does this solve the issue for you?
Does the dataTable.helpers.js file contain a definition for babelHelpers variable?

According to [this quick lookup in the code base](https://github.com/Swimlane/angular-data-table/search?utf8=%E2%9C%93&q=babelHelpers), the only occurence of "babelHelpers" is in the `release/dataTable.js` file.

**Comment by amcdnl** [comment]
@trusktr ya its hard to package es6 stuff. I'm not sure the 'best' way to do this. open to ideas

**Comment by trusktr** [comment]
My guess is just make babelHelpers a runtime dependency. 

``` bash
npm install package-that-provides-babel-helpers-whatever-that-is --save
```

then `require` or `import` it into your code.

**Comment by ghost** [comment]
As the [README pointed out](https://github.com/swimlane-contrib/angular-data-table#include), you can include `./release/dataTable.helpers.min.js` file and only this one.
It will contain the Babel runtime.

The `./release/dataTable.js` does not contain the Babel runtime, so you have to include it on your own.

**Comment by trusktr** [comment]
@kerbrat-quod I don't think that is the right solution. Using the `helpers.min.js` file means that the babel helpers will be duplicate if some other library also needs them. And, with the other file, it is expected for babel helpers to be global, which is also not best practice nowadays.

The best solution (if possible) is to `require` (or `import` if using ES6 syntax) the helpers into the code, and make the helpers a runtime dependency (not dev dependency). This way, if other packages/libraries also need to use the helpers, then they import the same helpers and there are no duplicates, and there is not need for global handling by the end user.

So, I'll re-open as I believe that would be the best approach to take (assuming babel helpers can be imported as a runtime dependency).

**Comment by trusktr** [comment]
The solution is here: http://www.2ality.com/2015/12/babel6-helpersstandard-library.html#babel-plugin-transform-runtime

**Comment by amcdnl** [comment]
Thanks for the link, we just need to upgrade this to babel 6 and repackage.

**Comment by marjan-georgiev** [comment]
Since version 0.5.0, we are including the babel helpers in all distributions of the library, so you won't have to include them separately.

For versions prior to 0.5.0, please use the dataTable.helpers.js file if you do not include them separately in your project.
