### ISSUE TITLE
Example demos not working.

### ISSUE THREAD

**Issue by matiaslabra** [Swimlane/angular-data-table#20]
Demos in http://swimlane.github.io/angular-data-table/ are not working for me.

**Comment by marjan-georgiev** [comment]
@MemoLabra 
Could you tell me which browser you're using please? Also, do you see any errors in the JS console? Could you post a screenshot?

Thanks!

**Comment by slamuu** [comment]
Doesn't work for me either, using latest chrome v43.0.2357.130

Error seems to be missing `define` for requirejs dependency

<img width="818" alt="inspector-console" src="https://cloud.githubusercontent.com/assets/6969344/8490953/e420367c-20e6-11e5-95a6-3aea164b4cf6.png">

**Comment by matiaslabra** [comment]
same @slamuu error log , Chrome 43.0.2357.130 (64-bit).

**Comment by amcdnl** [comment]
@marjan-georgiev lets update the demos now we have umd working.

**Comment by amritk** [comment]
+1

**Comment by Reklino** [comment]
It looks like the cdn.rawgit urls aren't loading in the codepen demos. I'm getting 404 errors.

**Comment by marjan-georgiev** [comment]
Demos should be working now.
