### ISSUE TITLE
Demos not working

### ISSUE THREAD

**Issue by darknasty** [Swimlane/angular-data-table#200]
It looks like none of your demos are working.

**Comment by jmls** [comment]
I concur .. nothing is working - must be a problem with the library

![image](https://cloud.githubusercontent.com/assets/929523/15273344/d4343c26-1a8d-11e6-9375-6d6a1e5d633c.png)

**Comment by jmls** [comment]
I have to say it's kinda worrying that this has been open at least three days ..

**Comment by marcfielding1** [comment]
Yeah the demos are trying to load the js and css from 
`http://swimlane.github.io/angular-data-table/lib/dataTable.helpers.js`

When it seems that folder doesn't exist!

**Comment by amcdnl** [comment]
Should be fixed now
