### ISSUE TITLE
watchers in angular-data-table

### ISSUE THREAD

**Issue by kuzman** [Swimlane/angular-data-table#202]
In my tables I don't use checkbox or tree column, but anyway I see a lot of watchers on 'cell.column.isCheckBoxColumn' and 'cell.column.isTreeColumn && cell.hasChildren'
I have 3 grids on the same view and the number of these types of watchers is 129 each

another type of watchers 'cell.styles()' and 'cell.cellClass()' their number is also 129 and one of the top consumers of time of the Digest cycle.

So from four type of watchers I have almost half of the total watchers in the observed view

What can I do to improve this? maybe you have something in mind to improve the perfs?

**Comment by agaurav** [comment]
This is something I have observed as well and is greatly impacting the performance of this otherwise great module. 
There is a sharp increase in number of watcher as well as the digest rate and time and noticeable freezes on scrolling when used with column templates.  
Below are the screenshots for some metric for a page having the same table (7 columns, 40 rows with pagination) using [ng-table](https://github.com/esvit/ng-table) vs one using this angular-data-table.

ng-table

![screen shot 2016-06-10 at 11 23 06 pm](https://cloud.githubusercontent.com/assets/1772870/15974061/2907ad24-2f64-11e6-9420-ae945394cc74.png)

angular-data-table

![screen shot 2016-06-10 at 11 23 21 pm](https://cloud.githubusercontent.com/assets/1772870/15974102/648e29b8-2f64-11e6-9108-afa771be02e3.png)

**Comment by agaurav** [comment]
@amcdnl were you able to look into this issue?

**Comment by amcdnl** [comment]
@agaurav I appologize, I have not ... I've actually never had any issues. We load it with 1-50k rows often and not had any slow down on perf. Are you using virtual scrolling or pagination?

We actually just launched the angular2 version of this ( https://github.com/swimlane/angular2-data-table ) I'm going to be dedicating most of my effort to, I'd encourage you to check that out. Given our migration to ng2, our support of this project will be limited. 

If you would like to make a PR I'd be happy to review and provide feedback!

**Comment by agaurav** [comment]
@amcdnl It doesn't look related to number of rows as the digest cycle is taking almost same time for ~50 as well as ~4K rows. Actually it's not even noticeable with a single table on page but with two or more the UI really slows down. I am using pagination with virtual scrolling as in this example http://codepen.io/marjan-georgiev/pen/vOebGw . 
I think it's important for ng2 version too, as the variables bound to DOM are still watched over in main thread. So unless you have made major changes in the component logic this issues might come up there as well.

Right now I am a bit tied up. I will try to go over the code next weekend and give a PR or some actionable insight.

**Comment by amcdnl** [comment]
@agaurav The ng2 version internals of the table are quite a bit different and im using 1 way binding in a few places and moving more to that too.

Ya, absolutely let me know what you come up w/, feel free to hit me up on gitter too.

**Comment by ghost** [comment]
Maybe resolved by #219.
If you have cellRenderer functions in you columns definitions, the html can create watchers that was never destroyed when the data was updated.
The PR fixes this by destroying the cell scope whenever the data updates, effectively removing watchers.
@agaurav Can you test with the 0.6.0 version, please?

**Comment by agaurav** [comment]
@kerbrat-quod Awesome, It's much better now. Thanks a lot @Charles-BARDIN .
The digest time has really improved.
![screen shot 2016-08-03 at 12 34 11 am](https://cloud.githubusercontent.com/assets/1772870/17341553/c0757678-5912-11e6-88a6-9039e3d47622.png)

**Comment by amcdnl** [comment]
Thanks everyone for your help!

**Comment by chenbojian** [comment]
@agaurav What's the tool are you using to monitor angular watchers?

**Comment by agaurav** [comment]
@chenbojian here is the GitHub repo of the tool https://github.com/Linkurious/angular-performance
