### ISSUE TITLE
Selection highlight for non-multiSelect tables

### ISSUE THREAD

**Issue by ghost** [Swimlane/angular-data-table#203]
Hi,

I found that the row highlight is enabled only if the `multiSelect` is set to `true`.
Here is a CodePen that shows the highlight selection: http://codepen.io/thomaskerbrat/pen/KMKrjj
And here is a CodePen that shows no highlight selection: http://codepen.io/thomaskerbrat/pen/beGOVZ

The only difference is this property:

``` js
multiSelect: false
```

Is this a feature or a bug?
I would like to have the highlight even if the table is not a multiSelect.

Thanks,

**Comment by ghost** [comment]
Hi,

I do not have the time to investigate your code base and make a PR.
Could you give me an update on this, please?

Regards,

**Comment by amcdnl** [comment]
I think you should be able to enable highlighting by turning `outline` on in css and adding appropriate CSS styles for outline. This is not a data-table feature.

If you would like to add this natively, I encourage you to submit a PR.
