### ISSUE TITLE
Using Angular filters in cellRenderer

### ISSUE THREAD

**Issue by darknasty** [Swimlane/angular-data-table#204]
How would one use Angular filters like {{amount | currency}} in the cellRenderer?   I tried adding 

 cellRenderer: function () {
                    return '<div>${{$cell | currency}}</div>';
                }

**Comment by ghost** [comment]
The solution you provided should work.
Using `$cell`, make sure you have declared the `prop` property in the column object you're in.
Alternatively, you can use `$row.yourPropertyName` to access your objects' properties.

``` js
columns: [
  {
    prop: 'yourPropertyName',
    cellRenderer: function () {
      return '$ {{$cell | currency}}';
      return '$ {{$row.yourPropertyName | currency}}';
    }
  }
]
```

If this doesn't work, could you provide a demo, please?

**Comment by darknasty** [comment]
Yes it worked.  I am not sure why it didn't for me the first time I tested it.  May have had a typo.  Thanks!
