### ISSUE TITLE
Data will not display; Loading message goes away, no error in console

### ISSUE THREAD

**Issue by getglad** [Swimlane/angular-data-table#207]
I have been able to build the demo, but when I try to use my own data, I can't get the 'data' part of the table to load. The columns load fine, the 'Loading...' message goes away, but the data never actually shows. There are no errors in the console.

If this is from the demo data set:

```
demoColumns = [ 
  {"name":"name"},
  {"name":"gender"},
  {"name":"company"},
]

$scope.demoData = [{
  "name":"Ethel Price",
  "gender":"female",
  "company":"Enersol"
}]
```

And this is from my data set:

```
sampleColumns = [
  {"name":"Composite"},
  {"name":"Num"},
  {"name":"FIXED"},
  {"name":"DT"},
  {"name":"ALT_DT"},
]

$scope.sampleData = [{
  " Amt ":"4",
  "Composite":"A",
  "Num":1,
  "FIXED":"Y",
  "DT":"5/3/2013",
  "ALT_DT":"5/3/2018"
}]
```

And my controller is this:

```
$scope.options = {
  rowHeight: 50,
  headerHeight: 50,
  footerHeight: false,
  scrollbarV: false,
  selectable: false,
  columns: one of the column variable names from above
};
```

And my view is this:

```
<dtable options="options" rows="data name from above" class="material"></dtable>
```

I get the below:
### Working example using demo data from above:

![working](https://cloud.githubusercontent.com/assets/2453555/16247931/d626a080-37d1-11e6-8e4b-92c28f7d58ef.png)
### Not working example using my sample data from above:

![not working](https://cloud.githubusercontent.com/assets/2453555/16247933/d91b1d0c-37d1-11e6-8272-8b7b7cd88cd0.png)

Is there something I am missing about my configuration here?

**Comment by amcdnl** [comment]
For that data, define the `prop` attribute on the column. Example: `{ "name": "ALT_DT", prop: "ALT_DT" }`. I bet the camelcase converter that converts the `name` to `prop` when not defined is not converting that correctly.

**Comment by getglad** [comment]
Yup - seems to be it. Thanks!
