### ISSUE TITLE
Thanks ❤️

### ISSUE THREAD

**Issue by danmindru** [Swimlane/angular-data-table#208]
Flippin' awesome code, thank you!

**Comment by amcdnl** [comment]
Thanks! 👍  ... Did you have any issues or anything?

**Comment by danmindru** [comment]
No issues whatsoever, just wanted to show my appreciation :-)

**Comment by amcdnl** [comment]
Thanks so much! We have a Angular2 version in the works too! https://github.com/swimlane/angular2-data-table

**Comment by danmindru** [comment]
Sweet! Gonna take it for a spin soon 🚗

**Comment by amcdnl** [comment]
Its very beta but PRs are very welcome ;)
