### ISSUE TITLE
Question - HTML column definition and header template

### ISSUE THREAD

**Issue by Charles-BARDIN** [Swimlane/angular-data-table#214]
Hi,

I used to define all my columns in the javascript. I recently saw in your README.md that we can define these column in the html like this :

``` js
<dtable options="options" rows="data" class="material dt">
  <column name="Name" width="300" flex-grow="2"></column>
  <column name="Gender">
    <strong>{{$row.name}}</strong>: {{$cell}}
  </column>
</dtable>
```

Do we have a way to set a template for the header with this approach ? Something equivalent to the `headerRenderer` function used when defining columns in the javascript side ?

Thank you

**Comment by amcdnl** [comment]
The only way for header templates is via the renderer. 

See: https://github.com/swimlane/angular-data-table/blob/master/demos/templates.html#L80

**Comment by publicbar** [comment]
Hi, I need to be able to put newlines in the heading tag. they are also dynamic. 

I notice we cannot do it just with the column, so I tried the headerRenderer which works until
I try passing in a value.

for (i=0;i<headings.length;i++){
headerRenderer: function(scope, elm){
                  return '<strong>'+headings[i].name+'</strong>';
                },
};

Any suggestions ?

Thanks
Chris
