### ISSUE TITLE
Adding/removing columns

### ISSUE THREAD

**Issue by Ruud-cb** [Swimlane/angular-data-table#215]
[enhancement]

First: I see a lot of open bugs or enhancements dating back to 2015. But I also see that the code has been edited 2 weeks ago. Maybe a good thing to resolve some?

Anyhow, I will probably use this library, one of the functionalities that I also need is to dynamically add and remove columns. As far as I can see this will be no problem because I can adjust the list in the controller and I will be fine. Perhaps this is something to think about and perhaps implement?

Something like a right-click context menu to select other columns (see windows explorer). A angular context menu could be used like this: https://github.com/Templarian/ui.bootstrap.contextMenu and because this doesn't work on IOS's force touch devices, could be combined with this: http://pressurejs.com/ 

One concern is how this would actually work out on mobile devices, I guess a better solution would be to have some kind of side-menu instead of a context menu.

Thoughts?

**Comment by amcdnl** [comment]
> "...I also see that the code has been edited 2 weeks ago"

The project is still very active, I just do not have time to address every bug reported that doesn't directly affect our internal usage.

> "Maybe good thing to resolve some?"

I gladly accept PRs, I will be happy provide feedback and direction.

> "I also need is to dynamically add and remove columns"

Please check the demos; we have this use case built already: https://github.com/swimlane/angular-data-table/blob/master/demos/columnadd.html

> "Perhaps this is something to think about and perhaps implement"

The demo above uses a decoupled menu control, I do NOT plan to couple that to the project nor a context menu. This project is aimed at enabling developers to present large and complex data in a flexible manner not solving specific use cases. Everyone will present that option in a different way and I don't want to bloat the project w/ all those cases. If thats what you want, look at other options I highlighted in the readme.

> " is how this would actually work out on mobile devices"

I have not tested this project on mobile devices, however, not really our use case either. Typically the amount of data and complexity of data this table is used to display is not ideal for any mobile UX scenario.
