### ISSUE TITLE
Rearrange columns bug

### ISSUE THREAD

**Issue by Ruud-cb** [Swimlane/angular-data-table#216]
I have been digging around for the past 3 hours, trying to find why it works perfectly on the website and not in my project.

Images say more then words:
![image](https://cloud.githubusercontent.com/assets/10037514/16840380/abc24b86-49d4-11e6-96c7-7f5b1c575dd7.png)

So after I rearranged, for a second it shows the old setup. Looks like it first adds the new row columns, and then deletes the old ones.
App:

```
var app = angular.module("flightapp", ['ngAnimate','data-table']);
```

Controller (different file):

```
var tableController = function ($scope) {

    var self = this;

    this.tableOptions = {
        rowHeight: 40,
        headerHeight: 50,
        footerHeight: false,
        columns: [{
            name: "Name",
            prop: "name",
            width: 200
        }, {
            name: "Gender",
            prop: "gender",
            width: 200
        }, {
            name: "Company",
            prop: "company",
            width: 200
        }]
    };

    this.data = [
    {
        "name": "Ethel Price",
        "gender": "female",
        "company": "Enersol"
    },
    {
        "name": "Claudine Neal",
        "gender": "female",
        "company": "Sealoud"
    },
    {
        "name": "Beryl Rice",
        "gender": "female",
        "company": "Velity"
    },//all the rest of 100.json
    ];

};
angular.module('flightapp').controller('tableController', ['$scope', tableController]);
```

cshtml (it is asp.net):

```
<link href="~/Content/material.css" rel="stylesheet" />
<link href="~/Content/dataTable.css" rel="stylesheet" />
<style>


    .dt {
      width: 100%;
      margin: 50px auto;
      height: 350px;
    }
    </style>
@{
    ViewBag.Title = "Tables";
}



<h2>Tables</h2>

<div class="container-fluid" ng-app="flightapp" ng-controller="tableController as tc">

        <dtable options="tc.tableOptions" rows="tc.data" class="material"></dtable>

</div>



@section scripts{

    <script src="~/Scripts/angular.js"></script>
<script src="~/scripts/angular-animate.min.js"></script>
<script src="~/scripts/external/dataTable.js"></script>
<script src="~/AngularJS/App.js"></script>
<script src="~/AngularJS/controllers/tableController.js"></script>
    }
```

All the functionality works fine, resize, rearrange, words cutoff if it is to long and styling. Yet this seems to be a problem. Am I missing a script?

I couldn't get the demo's to work because it is missing ../jspm_packages/system.js

**Comment by Ruud-cb** [comment]
I found the problem: Including angular ngAnimate caused the problem. Really frustrating...

**Comment by amcdnl** [comment]
I use ngAnimate in my project so not sure what caused that.

**Comment by msholly** [comment]
This is an old thread, but it might help someone with animation issues with angular-data-table. I had an issue where turning off and on columns or reordering them flashed content for a split second. I found my project had animate-enter and animate-leave, instead of the correct namespace of ng-enter and ng-leave. Must have copy pasted from an incorrect website somewhere. 

`.ng-leave.ng-leave-active {
    opacity: 0;
    width: 0px;
    height: 0px;
}
`

This CSS fixed the issue, and I have a feeling it might have been related to Ruud-cb's issue.
