### ISSUE TITLE
No search filtering is supported

### ISSUE THREAD

**Issue by nadeemkhoury** [Swimlane/angular-data-table#217]
Hello Guys, I'm using the selected row table, but I want to add search filter of the table, do you have this feature or not supported yet. 
Note: I know it is supported in material edition, but I want it without angular material.

**Comment by amcdnl** [comment]
There is no material edition, it's simply a theme and doesn't use material at all.

The grid just displays the data, use the filter example to filter your data and the grid will update. Cheers!

**Comment by nadeemkhoury** [comment]
Hello, 
can you send me the link of the filter example ?? I can't find it.

**Comment by ssubashchandran** [comment]
Just in case, someone is still searching, [here you go](https://github.com/swimlane/angular-data-table/blob/master/demos/filters.html)
