### ISSUE TITLE
Scope is not destroyed when the row is rerendered

### ISSUE THREAD

**Issue by Charles-BARDIN** [Swimlane/angular-data-table#218]
Hi,

We are using your data-table with the cellRenderer function.

In the cellRenderer function, we have a directive that has watchers.
When the cell rerenders, the scope is not destroyed and the watchers are still evaluated in the digest cycle.

The consequence is that the number of watchers grow every time an update is applied to the row's data. After a few minutes (depending on the number of updates by seconds), the ui is frozen.

**Comment by kuzman** [comment]
I have tested @Charles-BARDIN modifications and I was blown by the performance gain. Previously I had my watchers continuing to rise, with heavy updates even up to 20000 watchers.. Now the same test has less than 2000 watchers!

**Comment by amcdnl** [comment]
Merged! :)
