### ISSUE TITLE
Set paging count

### ISSUE THREAD

**Issue by nokkypx** [Swimlane/angular-data-table#231]
How can i set the paging count, the virtual paging sends a server request every 9 rows, i want to set it myself to every 1000 rows.
And also, would love it if i could set when to start the fetching.
i want the data fetch function to fire after 7% of the data has been seen.
currently i fetch the data only when 100% of the data has been scrolled into view

**Comment by amcdnl** [comment]
Sure! you can set the count on the paging object like this: https://github.com/swimlane/angular-data-table/blob/master/demos/paging.html#L84
