### ISSUE TITLE
Error: SyntaxError: Unexpected token <     

### ISSUE THREAD

**Issue by hellogithub2014** [Swimlane/angular-data-table#232]
hello, I started to learn angular 2 about  one week ago,  yesterday i was following the "angular2-data-table basic example" at [https://embed.plnkr.co/TLx2vYlCTLsqcLwvWafd?show=preview&autoCloseSidebar=true](url) , copied those codes to my app files,but when i used "npm start" to test, an error was appeared:
`(index):17 Error: SyntaxError: Unexpected token <(…)
(anonymous function) @ (index):17
ZoneDelegate.invoke @ zone.js:332
Zone.run @ zone.js:225
(anonymous function) @ zone.js:591
ZoneDelegate.invokeTask @ zone.js:365
Zone.runTask @ zone.js:265
drainMicroTaskQueue @ zone.js:497
ZoneTask.invoke @ zone.js:437`
I didn't know why this happened. Do I missed anything ??  thank everyone!
These are my files.   I build them based on "Angular 2 QuickStart",so i just show what i modified:

app.module.ts
`
/**
- Created by Administrator on 2016/9/1.
  */
  import { NgModule }      from '@angular/core';
  import { BrowserModule } from '@angular/platform-browser';
  import { AppComponent }  from './app.component';

import { Angular2DataTableModule } from 'angular2-data-table';

@NgModule({
    imports:      [ BrowserModule,Angular2DataTableModule ],
    declarations: [ AppComponent ],
    bootstrap:    [ AppComponent ]
})
export class AppModule { }
`

app.component.ts：
`
import {Component} from '@angular/core'

import { Angular2DataTableModule } from 'angular2-data-table';

import {
  TableOptions,
  TableColumn,
  ColumnMode
} from 'angular2-data-table';

@Component({
  selector: 'my-app',
  template: `
    <h1>My First Angular 2 App</h1>
    <div>
          <h3>basic</h3>
          <datatable
            class='material striped'
            [rows]='rows'
            [options]='options'>
          </datatable>
        </div>
`
})
export class AppComponent { 

```
rows = [];

options = new TableOptions({
  columnMode: ColumnMode.force,
  headerHeight: 50,
  footerHeight: 50,
  rowHeight: 'auto',
  columns: [
    new TableColumn({ prop: 'name' }),
    new TableColumn({ name: 'Gender' }),
    new TableColumn({ name: 'Company' })
  ]
});

constructor() {
  this.fetch((data) => {
    this.rows.push(...data);
  });
}

fetch(cb) {
   const req = new XMLHttpRequest();
   req.open('GET', 'https://npmcdn.com/angular2-data-table@0.2.0/assets/data/company.json');

   req.onload = () => {
     cb(JSON.parse(req.response));
   };

   req.send();
 }
```

}
`
systemjs.config.js：
`
/**
- System configuration for Angular 2 samples
- Adjust as necessary for your application needs.
  */
  (function(global) {
  // map tells the System loader where to look for things
  var map = {
    'app':                        'app', // 'dist',
    '@angular':                   'node_modules/@angular',
    'angular2-in-memory-web-api': 'node_modules/angular2-in-memory-web-api',
    'rxjs':                       'node_modules/rxjs',
    'angular2-data-table':        'node_modules/angular2-data-table',
  
  };
  // packages tells the System loader how to load when no filename and/or no extension
  var packages = {
    'app':                        { main: 'main.js',  defaultExtension: 'js' },
    'rxjs':                       { defaultExtension: 'js' },
    'angular2-in-memory-web-api': { main: 'index.js', defaultExtension: 'js' },
  };
  var ngPackageNames = [
    'common',
    'compiler',
    'core',
    'forms',
    'http',
    'platform-browser',
    'platform-browser-dynamic',
    'router',
    'router-deprecated',
    'upgrade',
  ];
  // Individual files (~300 requests):
  function packIndex(pkgName) {
    packages['@angular/'+pkgName] = { main: 'index.js', defaultExtension: 'js' };
  }
  // Bundled (~40 requests):
  function packUmd(pkgName) {
    packages['@angular/'+pkgName] = { main: 'bundles/' + pkgName + '.umd.js', defaultExtension: 'js' };
  }
  // Most environments should use UMD; some (Karma) need the individual index files
  var setPackageConfig = System.packageWithIndex ? packIndex : packUmd;
  // Add package entries for angular packages
  ngPackageNames.forEach(setPackageConfig);
  var config = {
    map: map,
    packages: packages
  };
  System.config(config);
  })(this);

`

by the way, i don't know how to update my angular 2 from RC5 to RC6.... ,my "package.json"  is:
`
{
  "name": "angular2-quickstart",
  "version": "1.0.0",
  "scripts": {
    "start": "tsc && concurrently \"npm run tsc:w\" \"npm run lite\" ",
    "lite": "lite-server",
    "postinstall": "typings install",
    "tsc": "tsc",
    "tsc:w": "tsc -w",
    "typings": "typings"
  },
  "license": "ISC",
  "dependencies": {
    "@angular/common": "2.0.0-rc.5",
    "@angular/compiler": "2.0.0-rc.5",
    "@angular/core": "2.0.0-rc.5",
    "@angular/forms": "0.3.0",
    "@angular/http": "2.0.0-rc.5",
    "@angular/platform-browser": "2.0.0-rc.5",
    "@angular/platform-browser-dynamic": "2.0.0-rc.5",
    "@angular/router": "3.0.0-rc.1",
    "@angular/router-deprecated": "2.0.0-rc.2",
    "@angular/upgrade": "2.0.0-rc.5",
    "systemjs": "0.19.27",
    "core-js": "^2.4.0",
    "reflect-metadata": "^0.1.3",
    "rxjs": "5.0.0-beta.6",
    "zone.js": "^0.6.12",
    "angular2-in-memory-web-api": "0.0.15",
    "bootstrap": "^3.3.6"
  },
  "devDependencies": {
    "concurrently": "^2.0.0",
    "lite-server": "^2.2.0",
    "typescript": "^1.8.10",
    "typings":"^1.0.4"
  }
}
`

**Comment by amcdnl** [comment]
This project is for angular1.
