### ISSUE TITLE
Readme refers to missing file

### ISSUE THREAD

**Issue by frodefi** [Swimlane/angular-data-table#25]
`./release/data-table.min.js` mentioned in the readme does not exist.

In addition, the files are named a little bit different too (`data-table.js` in readme, `dataTable.js` in folder).

**Comment by amcdnl** [comment]
Good catch! Thanks!!

**Comment by frodefi** [comment]
Still missing the mentioned file though (`./release/dataTable.min.js`).

Anyway, thanks for a great directive!

**Comment by amcdnl** [comment]
@frodefi Whoops, sorry about that!  Ya, join us in the gitter room, would love to hear some feedback!
