### ISSUE TITLE
Columns not showing but rows are visible

### ISSUE THREAD

**Issue by anisharknair** [Swimlane/angular-data-table#262]
I am using datatable in angular2.
When I am uisng the below demo data I am able to generate the table with columns and rows.
  Tabcolumns = [
    { name: 'Name' },
    { name: 'Company' },
    { name: 'Gender' }
];
  Tabrows = [
    { "name": 'Any', gender: 'Male', company: 'Swimlane' },
    { "name": 'Dany', gender: 'Male', company: 'KFC' },
    { "name": 'Molly', gender: 'Female', company: 'Burger King' },
  ];

But when I am getting my own data,I am not able to generate columns but rows are displaying correctly.
This is my column array.

<img width="116" alt="columns" src="https://cloud.githubusercontent.com/assets/5848157/21521256/50b09538-cd21-11e6-9cd9-5d3352cd9817.PNG">

this is my html part
`<ngx-datatable
        class="material striped"
        [rows]="rows"
        [columns]="Tabcolumns"
        [columnMode]="'force'"
        [headerHeight]="50"
        [footerHeight]="50"
        [rowHeight]="50" 
        [scrollbarH]="true">
      
        
      </ngx-datatable> `

this is the table generated.
<img width="900" alt="rows" src="https://cloud.githubusercontent.com/assets/5848157/21521308/d1be4238-cd21-11e6-8ebe-bb0d16c36dcd.PNG">
@amcdnl

**Comment by jonshaffer** [comment]
This issue might do better posted here: https://github.com/swimlane/ngx-datatable/issues/new
