### ISSUE TITLE
I want to realize table-data filtering

### ISSUE THREAD

**Issue by guo-guo** [Swimlane/angular-data-table#266]
I want to realize table-data filtering then I do something like this

`<dtable options="options" # rows="data | filter:192 " class="material" selected="selected" on-row-click="onRowClick(row)" on-select="onSelect(rows)" tools="cm/table/filter"> </dtable>`

But made some mistakes

**Comment by guo-guo** [comment]
I had to solve this problem   
```
 if(_.isEmpty($scope.newFiltval)){
         $scope.data =data;
   }
  else{
         $scope.data =$filter('filter')(data,$scope.newFiltval);
  }
```

**Comment by ssubashchandran** [comment]
Just incase somebody is searching, [Here you go](https://github.com/swimlane/angular-data-table/blob/master/demos/filters.html)
