### ISSUE TITLE
Make parent scope accessible from row templates?

### ISSUE THREAD

**Issue by brianfeister** [Swimlane/angular-data-table#32]
So I spent a long while today tinkering and integrating the data table.  Really like the direction but I'm not sure I might have a showstopper feature need.  Is there an undocumented feature that allows me to call parent controller functions? I'm looking at the `RowDirective` and it looks like you're doing isolate scope and not doing `bindToCotnroller`.  I'm guessing this would be not only a significant refactor, but also a sort of "policy change" from a design direction, so I'm not sure you're interested in going this direction with the project.  I have an `<md-menu>` with a number of contextual menu items for deleting, updating, and renaming the item in the row where the dropdown button is located.

**Comment by amcdnl** [comment]
Given our conversation, we are switching to `bindToController`.  Will this help solve this problem?

**Comment by brianfeister** [comment]
Yup.  This would be fixed by #33.
