### ISSUE TITLE
CellRenderer doesn't work with ng-click.

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#37]
*cellRenderer: function(scope,elm) {
            if(scope.row.types === 'SINGLE')
              return '<span>{{value}}</span>';
            else
              return `<md-button ng-click="showAccountHolder(this,$event)">{{value}}</md-button>`;
        }

ng-click - doesn't call the scope function showAccountHolder.

**Comment by amcdnl** [comment]
Can you make a plunkr demonstrating this?

**Comment by brianfeister** [comment]
Related to #43 and/or `bindToController` refactor? I had the same issues getting scope methods to execute from inside both `<column>` templates and `cellRenderer` functions
