### ISSUE TITLE
Multiple Sorts don't work right

### ISSUE THREAD

**Issue by amcdnl** [Swimlane/angular-data-table#4]
When you have multiple sorts going using client-side sorting, it doesn't work quite right.  Perhaps we should only have 1 sort available.

**Comment by amcdnl** [comment]
similar to #29

**Comment by jsheely** [comment]
I would recommend that multi column sorting by a required feature. It's not unusual for users to want to sort by at least two columns. Ex. Date & Price, Name & Date, etc.

Typically this is done by last one in has priority and the rest are secondary sorts that remember what they were last toggled too. 

I do think that having a configuration option to remember **N** number of column sort history would be nice.

**Comment by amcdnl** [comment]
fixed now
