### ISSUE TITLE
prop does not work as element attribute

### ISSUE THREAD

**Issue by frodefi** [Swimlane/angular-data-table#40]
`prop` attribute does not work, see this [codepen](http://codepen.io/frodefi/pen/WvPdPP)

``` html
<dtable options="options" rows="data" class="material">
      <column name="iName" prop="name" width="200"></column>
      <column name="iCompany" prop="company" width="200"></column>
</dtable>
```

**Comment by amcdnl** [comment]
Thanks for reporting.  I'd chk out this line: https://github.com/Swimlane/angular-data-table/blob/master/src/DataTableController.js#L54  .... we probably just need a add a manual mapping.

**Comment by frodefi** [comment]
Great, that did it, thanks :)
