### ISSUE TITLE
Error in console when cellRenderer contains ng-if

### ISSUE THREAD

**Issue by frodefi** [Swimlane/angular-data-table#41]
I don't know if this is a bug or not, since this works ok when ng-show is used instead of ng-if, but just in case: When cellRenderer contains something like this, with ng-if:

```
cellRenderer: function() {
        return '<b ng-if="value">{{value}}</b>';
}
```

And this appears down in the list so you need to scroll down to see it, then several errors are thrown:
"TypeError: Cannot read property 'insertBefore' of null"

See [this codepen](http://codepen.io/frodefi/pen/GJzyad). Scroll down to around row 20, "Barry Page", and check the console.

**Comment by amcdnl** [comment]
Thanks for reporting and making a plunkr!  PR's welcome, code to debug it would be in here: https://github.com/Swimlane/angular-data-table/blob/master/src/components/body/CellDirective.js#L61
