### ISSUE TITLE
Error when prop contains an object

### ISSUE THREAD

**Issue by frodefi** [Swimlane/angular-data-table#42]
For one of the columns I have not a value, but an object with some properties, and I would like to use it like this:

``` javascript
{
      name: "Logged In",
      prop: "userinfo",
      width: 200,
      cellRenderer: function() {
        return '{{value.loggedIn}} ';
      }
}
```

But this gives an error: `Error: [jqLite:nosel] http://errors.angularjs.org/1.3.14/jqLite/nosel`

[This codepen](http://codepen.io/frodefi/pen/GJzyad) demonstrates the issue.

**Comment by amcdnl** [comment]
Likely similar to #41

**Comment by amcdnl** [comment]
plz test on 0.2.0
