### ISSUE TITLE
Support Expressive Columns Inside Parent Directives using Transclusion

### ISSUE THREAD

**Issue by brianfeister** [Swimlane/angular-data-table#43]
From a chat with @amcdnl a few days back:

Angular has pulled transclude as the last param in a directive `compile` block, making it so that the place where columns are being stored in `element.columns` ([here](https://github.com/Swimlane/angular-data-table/blob/master/src/DataTableDirective.js#L25)) is lost because transclusion pulls this out of the template and then replaces it via a "clone" type action.  Since the element is cloned and re-created in the transclusion process, that means the arbitrary data stored in the DOM is lost. 

We should consider handling this a different way so that the expressive columns don't break with transcluded parent directives.

**Comment by amcdnl** [comment]
I believe this is fixed now

**Comment by brianfeister** [comment]
Yup!
