### ISSUE TITLE
Page click doesn't load the rows. pagenation doesn't work.

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#47]
i opened this url in my local mechine http://localhost:9000/demos/paging.html
when i click page 2,3,4... nothing happened. table doesn't take me to particular page. 
rows remains show the same data for page 1.

**Comment by frodefi** [comment]
Same with the paging example on http://swimlane.github.io/angular-data-table/

**Comment by amcdnl** [comment]
Should be resolve w/ 0.3.0
