### ISSUE TITLE
CHANGELOG.md

### ISSUE THREAD

**Issue by frodefi** [Swimlane/angular-data-table#49]
Would be nice to see whats new with v0.3 (and other new versions in the future).

**Comment by amcdnl** [comment]
Good idea, agree!

**Comment by juristr** [comment]
@amcdnl You should take a look at this: https://github.com/semantic-release/semantic-release
- automatically releases on NPM
- automatically releases on GitHub with nice changelogs generated from [conventional commit messages](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit).

(Planning to use it for angular-model-factory)

**Comment by juristr** [comment]
@amcdnl by assigning me to this, does that mean u like it and I should configure that? :wink:

**Comment by amcdnl** [comment]
doing this in release page now

**Comment by juristr** [comment]
@amcdnl did activate semantic-release?

**Comment by amcdnl** [comment]
no, just did a release page for now
