### ISSUE TITLE
scrollHelper take the wrong input element 

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#50]
I have two table in one screen.
 table1 and table2. 
 scrollHelper have only one instance for both tables.
if I click the page 2 in table 1 it change the table 2 results.

**Comment by amcdnl** [comment]
Good find! We should probably create an instance and attach it to the options.

**Comment by shreeram** [comment]
i have scenario have same options used for multiple tables in a page.

**Comment by shreeram** [comment]
could we able to create seperate instance for each table in page. so it will not clash other table.

**Comment by shreeram** [comment]
column resize also have same issue.

**Comment by amcdnl** [comment]
PR welcome

**Comment by amcdnl** [comment]
Fixed in latest release
