### ISSUE TITLE
Demo doesn't work - update version used in demo (always latest?)

### ISSUE THREAD

**Issue by juristr** [Swimlane/angular-data-table#52]
Hi,

I was just trying to use data-table, by trying to recreate the "Basic" example in the demo. It doesn't work though and it seems like the latest version breaks it. When I update the codepen example with the latest version from GitHub it gives the same kind of errors I'm seeing.

Codepen: http://codepen.io/anon/pen/bdJmzZ

**Comment by amcdnl** [comment]
Anyone else seeing this? I don't see it :(

**Comment by typeofweb** [comment]
Demo doesn't work.

**Comment by marjan-georgiev** [comment]
Should be working again now. 
http://codepen.io/marjan-georgiev/pen/eNGbxW

**Comment by juristr** [comment]
:+1:
