### ISSUE TITLE
Interference with angular material-design

### ISSUE THREAD

**Issue by andrea-vega** [Swimlane/angular-data-table#60]
I would love to use this data table, but as soon as I include the module in my app, features like toolbar's md-scroll-shrink, and md-backdrop from angular material design stop working.  Has anyone else experienced this?  I have tried to selectively comment out code to isolate the culprit, but no luck so far.

**Comment by andrea-vega** [comment]
I isolated the problem.  In function polyfill(fnName), Array.prototype.find and Array.prototype.findIndex being changed impact angular material design.  Is there a workaround for this?

**Comment by amcdnl** [comment]
@brianfeister is using material with this.  do you have it brian?

**Comment by brianfeister** [comment]
What version of ngMaterial? This issue doesn't sound familiar to me.

**Comment by brianfeister** [comment]
Sounds related to Babel helpers or transpilation. My main project uses Babel, so that may dodge the conflict with what this module does in terms of transpilation.

**Comment by andrea-vega** [comment]
I'm on the HEAD/master of angular material design -- currently 0.10.1.

**Comment by maxtechera** [comment]
Was this fixed or any workaround was found?

**Comment by amcdnl** [comment]
are you getting it too?

**Comment by andrea-vega** [comment]
@crazymunky I never found a workaround, personally.  I am going to keep my eye on this project and hope someone figures it out.  It would be ideal in my mind to use utilities like lodash instead of transpilation, but I understand ES6 is a major feature of this project.

**Comment by amcdnl** [comment]
If you create a demo showing this, I'm sure we can track it down
