### ISSUE TITLE
Unable to see sorting icon

### ISSUE THREAD

**Issue by sebastiandanilonr** [Swimlane/angular-data-table#61]
Hi there and thanks for this grid component,
I'm doing my first angular project and I'm using angular-material and your table component.
I have a couple of issues.
First, when sorting by clicking on a column name the little row icon that indicates the sorting order doesn´t appear, and second, the last column doesn´t show the full text.

I'm using your latest release and angular 1.4.4

Thanks for your help.

**Comment by amcdnl** [comment]
This is because the table styles that using font icons you likely did not include

**Comment by marcrowo** [comment]
I also had this problem. I fixed it by including the "icons.css" file that is present in the [codepen examples](http://codepen.io/marjan-georgiev/pen/eNGbxW).

[http://fontastic.s3.amazonaws.com/Jnf54BZCm7mSjGCxNRbfp3/icons.css](http://fontastic.s3.amazonaws.com/Jnf54BZCm7mSjGCxNRbfp3/icons.css)
