### ISSUE TITLE
cell template not getting compiled on scroll

### ISSUE THREAD

**Issue by msuntharesan** [Swimlane/angular-data-table#67]
When you scroll the cell templates are not compiling immediately. I think it's missing `$digest` or `$apply` somewhere.
Please see this [pen](http://codepen.io/vanthiyathevan/pen/jbNKJZ)

**Comment by tsolmonOtsu** [comment]
In ScrollerDirective, change $scope.$digest() with $scope.$apply()

**Comment by Thrilleratplay** [comment]
Changing  $scope.$digest() with $scope.$apply() does correct template compiling but at the cost of performance.

**Comment by marjan-georgiev** [comment]
Thanks @Thrilleratplay
