### ISSUE TITLE
getting undefined when selecting a single row using a checkbox

### ISSUE THREAD

**Issue by nelsongallardo** [Swimlane/angular-data-table#68]
If I try to select a single row using a checkbox, I'm getting an "undefined" as element selected, but if I set the property "headerCheckbox: true" and select all the elements clicking on the header checkbox, it works. It only happens with the checkboxes, the selection with a single click works.
It was working but today I updated to the last version, but now even if I go to previous versions it doesn't work.

**Comment by amcdnl** [comment]
Please create a demo.

**Comment by jsheely** [comment]
The issue is you renamed the variable to handle multiselect. So you need to pluralize the rows param in the directive template

**Updated code**
`this.body.onSelect({rows: [rows]});`

**Fixed directive**

```
<dtable options="options" rows="data" on-row-click="onRowClick(row)" class="material" on-select="onSelect(rows)" selected="selected"></dtable>
```

Note that this means that on-select will always return an array.
