### ISSUE TITLE
Pagination issue when scrolling down to top.(upward direction)

### ISSUE THREAD

**Issue by shreeram** [Swimlane/angular-data-table#79]
pagination issue.

let initially 5 pages available in table first page is showing. i click the 4th page. it leads to fourth page. after i scroll upward direction. table rows(data) not loaded until i reach the 3rd page. table seems empty in between 4th page to 3rd page transition.

**Comment by amcdnl** [comment]
demo plz?

**Comment by Thrilleratplay** [comment]
I have an idea of what is causing this issue.

The on-page watch in the body controller is looking for an offset based on the first element of the page.  I am guessing @shreeram is using custom pagination to jump to page 4 then scrolling up into where page 3 should be but will not load until reaching the offset of page 3's first row.

I ran into a semi-related issue when trying to use on-page for infinite scroll.  My "fetch next page" function was triggered using on-page, but it will load the next page when I scroll up through previous pages.

**Comment by amcdnl** [comment]
@Thrilleratplay here is an example of how i handle that type of stuff - https://gist.github.com/amcdnl/5014a8ddd65182a8a7f8

**Comment by amcdnl** [comment]
I think @marjan-georgiev fixed it w/ this - https://github.com/Swimlane/angular-data-table/commit/64451a26fd2caa838d8773cd719d9ba7684833bb

**Comment by marjan-georgiev** [comment]
This should be fixed in 0.3.18
