### ISSUE TITLE
Column reordering on example page doesn't work

### ISSUE THREAD

**Issue by frontich** [Swimlane/angular-data-table#80]
Hello

I tried to reorder columns from  example  http://codepen.io/marjan-georgiev/pen/bdozep  in the following manner :
1. pull Gender column behind the Age  column
2. pull Age column in front of the Name column

The result is : 
- Name column gets data that belong to Company column, 
- Gender column gets data that belong Name column,  
- Company column gets no data at all, 
- Department column gets data that belong to Gender column

**Comment by bojanbass** [comment]
Exactly the same happened to me, looks like there's a bug.

**Comment by marjan-georgiev** [comment]
This has already been fixed. The examples are out of date. I'm going to be updating them soon.

**Comment by Fr0ntich** [comment]
Until you update examples what can i do to make it work? Any workaround?

**Comment by frontich** [comment]
I think there isnt just problem in the example page.  I made fiddle to make my point : 

https://jsfiddle.net/eoyc3Lfw/1/

The same thing that happens on example page happens also at my the fiddle.
- drag column ONE behind column FOUR 
- drag column FIVE to the front 

This is the result :

![data-table](https://cloud.githubusercontent.com/assets/13329466/10039987/b11968b6-61d7-11e5-94ca-42958d2242c8.png)

I am using  files from Swimlane/angular-data-table/tree/master/release [version 0.3.18]
I guess it is a bug.

**Comment by marjan-georgiev** [comment]
You're right. I see that too. I'll take a look.

**Comment by frontich** [comment]
@marjan-georgiev Howdy ... i am wondering if there are any news about this one?

**Comment by frontich** [comment]
@marjan-georgiev,  @amcdnl   ..i think i can help you with the code....

in dataTable.helpers.js file (release version), there seems to be the problem at line  1452

``` javascript

function onDragEnter(e) {
    var target = e.target;
    if (isbefore(dragEl, target)) {
       target.parentNode.insertBefore(dragEl, target);
    } else if (target.nextSibling && target.hasAttribute("draggable")) {
        // problem in the following line
        target.parentNode.insertBefore(dragEl, target.nextSibling); 
    }
  };

```

target.nextSibling returns 

``` html
<!-- end ngRepeat: column in header.columns['center'] track by column.$id -->
```

which is of type Node.COMMENT_NODE and if i understand ng-repeat right it will ALWAYS be at that position. Even if no data will be inside ng-repeat directive.

You have two solutions : 
- first you can chane  problematic line with  

``` javascript
target.parentNode.insertBefore(dragEl, target.nextSibling.nextSibling); 
```

which will return expected element for you ...or... 
- You can check Node.NodeType and then act accordingly

**Comment by marjan-georgiev** [comment]
Demo has been updated.

http://codepen.io/marjan-georgiev/pen/bdozep

**Comment by pgrm** [comment]
Hey, you should update the javascript reference in the codepen demos:

> http://swimlane-contrib.github.io/angular-data-table/lib/dataTable.helpers.js

instead of

> http://swimlane.github.io/angular-data-table/lib/dataTable.helpers.js
