### ISSUE TITLE
Explicit annotations missing in ES6 version

### ISSUE THREAD

**Issue by katrotz** [Swimlane/angular-data-table#82]
The DataTable is missing explicit annotations in ES6 version inside the release, hence an ES6 based angular project can not run in `strictDi` mode:

`Error: [$injector:strictdi] DataTableDirective is not using explicit annotation and cannot be invoked in strict mode`

Although this is not a critical issue as the transpiled version `dataTable.helpers.js`  can be used, I thought it should have been mentioned.

**Comment by amcdnl** [comment]
"ngInject" should setup the annotations, probably just a missing tag somewhere.

**Comment by amcdnl** [comment]
Are you still getting this?

**Comment by katrotz** [comment]
@amcdnl The issue can be closed. It is reproducible only with the unbuild ES6 file from the release.

**Comment by Larchy** [comment]
I've also ran into this trying to pull in the ES6 version into an ES6 application that does it's own babel'ing. It would be nice to to able to pull this in with strictDi set. Going to switch to using the pre-transpiled version for now as well.

**Comment by amcdnl** [comment]
Ya, we are going to upgrade to babel6 this week and should resolve some of these issues.
