### ISSUE TITLE
The demo site does not work.

### ISSUE THREAD

**Issue by mrtinkz** [Swimlane/angular-data-table#87]
Hi,

Looks like the demo http://swimlane.github.io/angular-data-table/ is not working. I do not see the grid content, not sure but below is the error i see in my console. 

```
at XMLHttpRequest.D.onload (angular.min.js:86)(anonymous function) @ angular.min.js:102
```

**Comment by amcdnl** [comment]
dupe of #52

**Comment by mrtinkz** [comment]
Got it, thanks
