### ISSUE TITLE
Homepage is broken

### ISSUE THREAD

**Issue by lookfirst** [Swimlane/angular-data-table#90]
http://swimlane.github.io/angular-data-table/

TypeError: Cannot read property 'internal' of undefined
    at HeaderController.styles (dataTable.helpers.js:1298)
    at angular.min.js:198
    at Object.<anonymous> (angular.min.js:109)
    at l.$digest (angular.min.js:123)
    at l.$apply (angular.min.js:126)
    at l (angular.min.js:81)
    at S (angular.min.js:85)
    at XMLHttpRequest.D.onload (angular.min.js:86)

**Comment by amcdnl** [comment]
Does this happen when u run it locally?

**Comment by lookfirst** [comment]
No, this is what happens when I go to the above mentioned website. =)

**Comment by wmichaelfeltman** [comment]
I thought this was a known issue. None of the samples have worked on Chrome for several days. They work fine on IE 11.

**Comment by cranesandcaff** [comment]
Is it site only? The codepen didn't work either.

**Comment by snarayanank2** [comment]
Same here. Demo on this [page](http://swimlane.github.io/angular-data-table/) doesn't work on Chrome or Safari on Mac. Doesn't work on codepen either. Can someone confirm that things work for them locally on all browsers? FYI on Chrome, I see this error:

```
Uncaught ReferenceError: babelHelpers is not defined
```

**Comment by iagopiimenta** [comment]
+1

**Comment by f1tech** [comment]
Why is this closed? Are you really planning not to support Chrome? Actually currently the home page for the demo doesn't work on Chrome 46.x, Firefox 40.0.3 and ie 11. Some of the demos work on some of the browsers, but all Browsers seem to have issues with at least a few of the demos.

**Comment by marjan-georgiev** [comment]
@f1tech  This isn't closed. #88 is, which is a duplicate of this.

**Comment by adam-g-pullen** [comment]
+1

**Comment by marjan-georgiev** [comment]
Demos should be working again.

**Comment by harrisrobin** [comment]
I am also getting `Uncaught ReferenceError: babelHelpers is not defined` and I am on version 
`@version v0.4.8`

**Comment by stoplion** [comment]
Getting similar errors whenever adding `dataTable.helpers.js` to my project. 
[I filed a similar issue](https://github.com/Swimlane/angular-data-table/issues/127#event-511566443) with more details.

**Comment by amcdnl** [comment]
shuld be fixed now

**Comment by mach-kernel** [comment]
+1, trying to use with Angular 1.4.2 without any luck.
