### ISSUE TITLE
QUESTION: Does angular-data-table not support editable cells?

### ISSUE THREAD

**Issue by bastienJS** [Swimlane/angular-data-table#92]
I could not find a way to configure the datatable with editable cells.

Is that true or do I like at the wrong place?

**Comment by amcdnl** [comment]
Editable cells are implementation specific. Unlike other solutions this does not make assumptions about your data or implementation and therefore doesn't bloat it with components that differ based in implantation.

You can totally implement this with cell templates, I actually posted a sample in my last commit in the demos

**Comment by bastienJS** [comment]
Yes but with cell templates EVERY developer would have to care for its own material design implementation for Edit/Display template. For that we have control vendor or open source ;-) DRY not WET.

**Comment by amcdnl** [comment]
Every developers implementation is different; one size does not fit all. Implementing your own cell template is pretty minimal and gives you full control with no weight of what my implementation might have been for this project. This is not something I will be implementing with this project, sorry.

**Comment by amcdnl** [comment]
@bastienJS check out this demo i did for how to do this - https://github.com/Swimlane/angular-data-table/blob/master/demos/inline-editing.html
