### ISSUE TITLE
Refreshing the data table

### ISSUE THREAD

**Issue by wmichaelfeltman** [Swimlane/angular-data-table#93]
I have a data table that's working properly. It's rows property is set to an an array in my controller named lineItems. I'm using controllerAs syntax, so it's actually set to order.lineItems. I have another non-angular-data-table list of items that assigns values to the currentRow in the data table when double clicked. This code looks like this:

```
// $scope.$apply(function () {
           vm.lineItems[vm.selectedRow.$$index].foundItem = product.stk_num;
           vm.lineItems[vm.selectedRow.$$index].title = product.title;
           vm.lineItems[vm.selectedRow.$$index].foundBy = "Cart Search";
// })
```

The values all update properly, but the data table is not refreshed. If I uncomment out the $scope.$apply function I receive this error: Error: $rootScope:inprog
Action Already In Progress.

If I scroll the data table, then it's updated. 

I'm not sure if you'd consider this a bug or not. Is there a function I can call to update the data table?

**Comment by amcdnl** [comment]
Try $timeout ...

**Comment by wmichaelfeltman** [comment]
$timeout doesn't work either. I should have mentioned that I had already tried that as well.
