### ISSUE TITLE
decouple the project from jspm

### ISSUE THREAD

**Issue by vladimir-ivanov** [Swimlane/angular-data-table#94]
hi, it would be very beneficial to decouple the project form jspm - e.g. to use with webpack or other solutions.

**Comment by amcdnl** [comment]
you don't have to use jspm, use the raw es6 and have fun

**Comment by vladimir-ivanov** [comment]
ok, the issue we are facing is - running npm install - which runs jspm 
  "scripts": {
    "postinstall": "jspm install"
  }

would be nicer if that is not a postinstall script (I know we could run npm install --ignore-scripts :-)

**Comment by marjan-georgiev** [comment]
You don't need to run that unless you want to contribute to the project.

For consumption, you can use one of the release packages suitable to your setup and import it in your application. https://github.com/Swimlane/angular-data-table/tree/master/release

If you use webpack with babel, just import dataTable.es6.js and the stylesheet and you should be good to go.

**Comment by vladimir-ivanov** [comment]
surely - except we are using package.json in our project which includes yours - so we bring all the dependencies in via running npm install (which is the only allowed/supported package manager for js stuff at the moment) and sadly we are not allowed to clone external git repos either (pretty common setup in corporate environments :-()

**Comment by marjan-georgiev** [comment]
Ah, good point. We'll remove the postinstall script shortly.

**Comment by vladimir-ivanov** [comment]
great, thank you :-)

**Comment by amcdnl** [comment]
done.
