### ISSUE TITLE
Persistent resizing

### ISSUE THREAD

**Issue by harrisrobin** [Swimlane/angular-data-table#96]
First of all, this is hands down the best data table for angular out there. I almost chose integrating react in my app just to use facebook's fixed-data-table until I saw this.

There is one feature I would like that i missing though and it is the ability to persist resizing. So in my use case, my users would resize their tables a certain way and it would be important for me to make sure the table looks the same way every time they come back to the app. Let me know if anyone see's this as being a useful use case as well!

**Comment by amcdnl** [comment]
@HarrisRobin Thanks a lot, it was partly inspired by that project ;).

You say persistant resizing, do you mean columns or the height/width of the grid?

**Comment by harrisrobin** [comment]
Yes, I mean the column. This has a lot of good uses cases for me as we are displaying a lot of data on these tables so having to resize everytime can be annoying. I am planning on giving it a shot after I get a chance to take a look at your code to see if I can come up with something :)

**Comment by amcdnl** [comment]
Oh, thats easy.  You can set the widths here: https://github.com/Swimlane/angular-data-table/blob/master/src/defaults.js#L106 then just observe the change and save it to your data store of your choice and on re-render fetch and set.
