### ISSUE TITLE
Should user-select:none be default?

### ISSUE THREAD

**Issue by jsheely** [Swimlane/angular-data-table#98]
https://github.com/Swimlane/angular-data-table/blob/master/src/dataTable.less#L38-L42

```
-webkit-user-select: none;
    -moz-user-select: none;
    -ms-user-select: none;
    -o-user-select: none;
    user-select: none;
```

The default dataTable.css contains a css property _user-select:none_. Any reason particular reason that is the default and should it be?

I find it handy to be able to select text from a row to copy and paste it into something else. This inhibits that ability. I know we can override it but just wonder if it should really be the default.

**Comment by amcdnl** [comment]
I had some specific reason for doing it but i can't remember now.  You can always override it in your implementation.
